name: "Database Workflow"

on: 
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
    secrets:
      aws-assume-role-arn:
        required: true
      aws-region:
        required: true
      aws-statefile-s3-bucket:
        required: true
      aws-lock-dynamodb-table:
        required: true
      db_name:
        required: true
      db_username:
        required: true
      db_password:
        required: true
      allowed_cidr:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-assume-role-arn }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.aws-region }}

      - name: Read destroy config
        id: read-destroy-config
        run: |
          DESTROY="$(jq -r '.${{ inputs.environment }}' ./infra/terraform/destroy_config.json)"
          echo "destroy=$(echo $DESTROY)" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: |
          cd infra/terraform && terraform init \
            -backend-config="bucket=${{ secrets.aws-statefile-s3-bucket }}" \
            -backend-config="key=${{ github.event.repository.name }}" \
            -backend-config="region=${{ secrets.aws-region }}" \
            -backend-config="dynamodb_table=${{ secrets.aws-lock-dynamodb-table }}" \

      - name: Terraform Validate
        run: cd infra/terraform && terraform validate

      - name: Terraform Destroy
        if: steps.read-destroy-config.outputs.destroy == 'true'
        id: terraform-destroy
        env:
          TF_VAR_db_name: ${{ secrets.db_name }}
          TF_VAR_db_username: ${{ secrets.db_username }}
          TF_VAR_db_password: ${{ secrets.db_password }}
          TF_VAR_allowed_cidr: ${{ secrets.allowed_cidr }}
        run: cd infra/terraform &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform destroy -var-file="./envs/${{ inputs.environment }}/terraform.tfvars" -auto-approve

      - name: Terraform Plan
        if: steps.read-destroy-config.outputs.destroy != 'true'
        id: terraform-plan
        env:
          TF_VAR_db_name: ${{ secrets.db_name }}
          TF_VAR_db_username: ${{ secrets.db_username }}
          TF_VAR_db_password: ${{ secrets.db_password }}
          TF_VAR_allowed_cidr: ${{ secrets.allowed_cidr }}
        run: cd infra/terraform &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform plan -var-file="./envs/${{ inputs.environment }}/terraform.tfvars" -out="${{ inputs.environment }}.plan"

      - name: Terraform Apply
        if: steps.read-destroy-config.outputs.destroy != 'true'
        id: terraform-apply
        env:
          TF_VAR_db_name: ${{ secrets.db_name }}
          TF_VAR_db_username: ${{ secrets.db_username }}
          TF_VAR_db_password: ${{ secrets.db_password }}
          TF_VAR_allowed_cidr: ${{ secrets.allowed_cidr }}
        run: cd infra/terraform &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform apply "${{ inputs.environment }}.plan"

      - name: Get Terraform Output (Encode Base64)
        id: get-output
        if: steps.read-destroy-config.outputs.destroy != 'true'
        run: |
          cd infra/terraform

          RDS_ENDPOINT_RAW=$(terraform output -raw rds_endpoint)
          
          RDS_ENDPOINT_CLEAN=$(echo "$RDS_ENDPOINT_RAW" | cut -d: -f1)

          RDS_ENDPOINT_ENCODED=$(echo -n "$RDS_ENDPOINT_CLEAN" | base64 -w 0)

          echo "DEBUG: Hostname Limpo (pré-encode): $RDS_ENDPOINT_CLEAN"
          echo "DEBUG: Hostname Codificado (Base64): $RDS_ENDPOINT_ENCODED"
          
          if [ -z "$RDS_ENDPOINT_CLEAN" ]; then
              echo "::error::O output 'rds_endpoint' está vazio. Verifique se 'terraform apply' foi executado e se o output está definido no seu código Terraform."
              exit 1
          fi

          echo "rds_endpoint=$RDS_ENDPOINT_ENCODED" >> $GITHUB_OUTPUT

      - name: Decode DB_HOST and Set Environment Variable
        id: decode_host
        run: |
          ENCODED_HOST="${{ steps.get-output.outputs.rds_endpoint }}"
          
          DECODED_HOST=$(echo "$ENCODED_HOST" | base64 -d)
          
          echo "DEBUG: Hostname Decodificado: $DECODED_HOST"
    
          echo "DB_HOST=$DECODED_HOST" >> $GITHUB_ENV

      - name: Run Database Scripts
        if: steps.read-destroy-config.outputs.destroy != 'true'
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USERNAME }}
          DB_PASS: ${{ secrets.DB_PASSWORD }}
        run: |
          cd infra/scripts

          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          python run_scripts.py